#!/usr/bin/env bash
# Hold the reference implementation to its latest release, and the fixtures to it.
#
# ranke-go is what this library mirrors, so testing against a stale one is testing against
# a reference that has moved. Two ways that goes wrong, and this checks both:
#
#   tools/go.mod behind the latest release — the fixtures were generated by an older
#   reference implementation, so agreeing with them says less than it appears to.
#
#   the fixtures' recorded version behind tools/go.mod — the pin moved and nothing
#   regenerated, so the bytes came from a ranke-go this tree no longer names. Nothing else
#   catches this: the suite compares against the fixtures, whatever produced them.
#
# It reports rather than repairs. Bumping the pin regenerates every id, which is a change
# to review and not a thing to have happen inside a gate.
#
# The version is asked of the module proxy over HTTP, not of `go list`: `make fixtures`
# needs a Go toolchain and is deliberately outside `verify` for it, and a freshness question
# should not drag one back in.
#
# RANKE_GO_LATEST names the version to compare against, for working offline or ahead of a
# release.
set -euo pipefail

cd "$(dirname "$0")/.."

gomod="tools/go.mod"
fixtures="src/testing/claim_fixtures.json"
module="github.com/flocko-motion/ranke-go"

pinned="$(grep -oE "$module v[0-9]+\.[0-9]+\.[0-9]+" "$gomod" | grep -oE 'v[0-9.]+' | head -n1)"
if [ -z "$pinned" ]; then
	echo "ranke-go: $gomod names no released $module" >&2
	exit 1
fi

generated="$(grep -oE '"rankeGo": *"v[0-9]+\.[0-9]+\.[0-9]+"' "$fixtures" | grep -oE 'v[0-9.]+' | head -n1)"
if [ -z "$generated" ]; then
	echo "ranke-go: $fixtures records no generating version — run 'make fixtures'" >&2
	exit 1
fi

latest="${RANKE_GO_LATEST:-}"
if [ -z "$latest" ]; then
	# An unreachable proxy is a failure, not a pass: a check that cannot learn the latest
	# release has not compared anything against it.
	latest="$(curl -fsS "https://proxy.golang.org/$module/@latest" 2>/dev/null |
		grep -oE '"Version":"v[0-9]+\.[0-9]+\.[0-9]+"' | grep -oE 'v[0-9.]+' | head -n1)"
fi
if [ -z "$latest" ]; then
	echo "ranke-go: cannot reach the module proxy — set RANKE_GO_LATEST to compare offline" >&2
	exit 1
fi

status=0

if [ "$generated" != "$pinned" ]; then
	cat >&2 <<-MSG
		ranke-go: the fixtures came from $generated, $gomod names $pinned —
		the pin moved and nothing regenerated. Run:

		  make fixtures
	MSG
	status=1
fi

if [ "$pinned" != "$latest" ]; then
	cat >&2 <<-MSG
		ranke-go: $gomod names $pinned, the latest release is $latest —
		this library mirrors ranke-go, so the reference has moved and these tests
		have not been run against it. Read what changed, then:

		  cd tools && go get $module@$latest && cd .. && make fixtures
	MSG
	status=1
fi

if [ "$status" -eq 0 ]; then
	echo "ranke-go: $pinned, the latest release, and the fixtures came from it"
fi
exit "$status"
