import assert from 'node:assert/strict'
import test from 'node:test'

import { type Claim, contributorOf } from './claim.ts'
import { decodeClaim } from './codec.ts'
import { contentSize } from './content.ts'
import { hashContent, parseId } from './id.ts'
import { compareBytes } from './internal/cbor.ts'
import {
  type ArtifactSet,
  type ClaimCase,
  ReasonIDMismatch,
  ReasonWrongMessage,
  readArtifact,
  resolveArtifacts,
} from './testing/testdata.ts'

// The published artifact set is the spec's, not either implementation's, so running
// it here is what lets ranke-ts fail conformance. It is also the only reference data
// in this repository carrying cases that must be REFUSED — agreement on what to
// accept says nothing about what a reader lets through.
//
// Three cases turn on a signature, and this library holds no keys, so it cannot
// decide them. Each is named below, so a case that becomes undecidable for a new
// reason fails this file.
const NEEDS_A_KEY = new Set([
  'claims/rejected-wrong-message.cbor',
  'claims/rejected-wrong-signer.cbor',
  // Content altered after signing, so H(S(v)) moved. Under a signature id, telling
  // that apart from a valid claim needs the contributor's key.
  'claims/rejected-tampered-content.cbor',
])

let artifacts: ArtifactSet | null = null

async function set(): Promise<ArtifactSet> {
  artifacts ??= await resolveArtifacts()
  return artifacts
}

test('the artifact set resolves', async () => {
  const { manifest, origin } = await set()
  assert.ok(manifest.claims.length > 0, 'a set with no claim cases proves nothing')
  assert.ok(manifest.content.length > 0, 'a set with no content cases proves nothing')
  console.log(
    `artifact set from ${origin}, generated by ${manifest.provenance.generator} ` +
      `${manifest.provenance.version} at ${manifest.provenance.generated_at}`,
  )
})

/**
 * Outcome is what this library made of one case, beside what the manifest expected —
 * the same shape ranke-go's internal/vectors reports.
 */
interface Outcome {
  file: string
  expected: boolean
  accepted: boolean
  reason: string
  why: string
}

// closureOf loads every case the manifest calls valid, which is the graph a reference
// must resolve within. The set holds exactly what it calls valid, so a contributor
// resolves only when the set carries it.
function closureOf(a: ArtifactSet): Map<string, Claim> {
  const out = new Map<string, Claim>()
  for (const c of a.manifest.claims) {
    if (!c.verify) continue
    out.set(c.id, decodeClaim(readArtifact(a.root, c.file), c.id))
  }
  return out
}

// signerOf resolves the claim holding the key that signed c: c itself for an initial
// node, else the contributor its contribution/contributor edge names (§5.7).
function signerOf(c: Claim, closure: Map<string, Claim>): Claim | undefined {
  const contributor = contributorOf(c)
  return contributor === null ? c : closure.get(contributor)
}

/**
 * accepts applies the rules a reader can decide without a key: the bytes decode; an
 * identity-signed id equals the hash of its own preimage and its signer publishes no
 * key; every reference resolves; and the height is one above the highest it cites.
 *
 * The signature itself is out of scope, so a claim failing only there is accepted
 * here — which is why NEEDS_A_KEY exists.
 */
function accepts(a: ArtifactSet, c: ClaimCase, closure: Map<string, Claim>): boolean {
  let claim: Claim
  let raw: Uint8Array
  try {
    raw = readArtifact(a.root, c.file)
    parseId(c.id) // malformed_id: the pairing is part of what a case asserts
    // edgeIds, since V-EORDER below compares them. Opt-in on the read path, so a caller
    // that never addresses an edge pays no digest for one.
    claim = decodeClaim(raw, c.id, { edgeIds: true })
  } catch {
    return false
  }

  // `V-ID`: the id is H over the record as stored, so it is checkable with no key at all —
  // where it used to be a signature, and only an identity-signed claim could be checked
  // this way. Every case now answers here, and only `V-SIG` needs a contributor resolved.
  if (!hashContent(raw).equal(parseId(c.id))) return false

  // `V-EORDER`: the edges of the record AS STORED ascend by id(e). ranke-go checks this in
  // its verifier, so it belongs here rather than in the decoder, which would pay a digest
  // per edge on every read. Equal neighbours pass — the rule admits them.
  const ids = claim.edges.map((e) => e.id)
  for (let i = 1; i < ids.length; i++) {
    const previous = ids[i - 1]
    const current = ids[i]
    if (previous === undefined || current === undefined) return false
    if (compareBytes(parseId(previous).rawBytes(), parseId(current).rawBytes()) > 0) return false
  }

  let max = 0
  for (const e of claim.edges) {
    const target = closure.get(e.reference)
    if (target === undefined) return false // `V-REF`: a reference resolves in the closure
    if (target.height > max) max = target.height
  }
  const want = claim.edges.length === 0 ? 0 : max + 1
  return claim.height === want // §4.1
}

test('every decidable claim case lands as the manifest says', async () => {
  const a = await set()
  const closure = closureOf(a)
  const outcomes: Outcome[] = []

  for (const c of a.manifest.claims) {
    if (NEEDS_A_KEY.has(c.file)) continue
    outcomes.push({
      file: c.file,
      expected: c.verify,
      accepted: accepts(a, c, closure),
      reason: c.reason,
      why: c.why,
    })
  }

  const failures = outcomes
    .filter((o) => o.expected !== o.accepted)
    .map((o) => `${o.file}: expected verify=${o.expected}, got ${o.accepted} (${o.reason}) — ${o.why}`)
  assert.deepEqual(failures, [])

  // Guard the guard: if the accept cases were all that ran, this file would prove
  // only that valid claims decode.
  const refused = outcomes.filter((o) => !o.expected)
  assert.ok(refused.length >= 4, `expected refusal cases, got ${refused.length}`)
})

// Content integrity is the whole of §5.10 and needs no key at all: the bytes either
// hash to the name they are filed under or they do not.
test('every content case hashes to the name it is filed under', async () => {
  const a = await set()
  const failures: string[] = []
  for (const c of a.manifest.content) {
    const bytes = readArtifact(a.root, c.file)
    const matched = hashContent(bytes).toString() === c.hash
    if (matched !== c.verify) {
      failures.push(`${c.file}: expected verify=${c.verify}, got ${matched} — ${c.why}`)
    }
  }
  assert.deepEqual(failures, [])
})

// The three undecidable cases must still be present and still be refusals: if the set
// ever marks one valid, this library's silence about it stops being harmless.
test('the cases needing a key are refusals in the manifest', async () => {
  const a = await set()
  for (const file of NEEDS_A_KEY) {
    const c = a.manifest.claims.find((x) => x.file === file)
    assert.ok(c !== undefined, `${file} is missing from the manifest — revisit NEEDS_A_KEY`)
    assert.equal(c.verify, false, `${file} is now expected to verify`)
    assert.ok(
      [ReasonWrongMessage, ReasonIDMismatch].includes(c.reason),
      `${file} is refused for ${c.reason}, which may now be decidable without a key`,
    )
  }
})

// Every case is either decided or named. A new case appearing in a published set must
// be classified deliberately rather than counted as passing.
test('no case is silently ignored', async () => {
  const a = await set()
  const decided = a.manifest.claims.filter((c) => !NEEDS_A_KEY.has(c.file)).length
  assert.equal(
    decided + NEEDS_A_KEY.size,
    a.manifest.claims.length,
    'a claim case is neither decided nor named as needing a key',
  )
  console.log(
    `${decided} of ${a.manifest.claims.length} claim cases decided without keys, ` +
      `plus ${a.manifest.content.length} content cases`,
  )
})
